config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  # ユーザー作成
  get '/signup', to: 'users#new'
  
  # ログイン機能
  
  # ログインページ表示
  get '/login', to: 'sessions#new'
  
  # ログイン情報送信
  post '/login', to: 'sessions#create'

  # ログアウト
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100 },
                    format: {with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil) #データベースの情報(:remember_digestを破棄)
  end
  
  def self.search(search)
    if search
      User.where(['content LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :edit_basic_info, :update_basic_info, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :edit_basic_info, :update_basic_info, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :edit_basic_info, :update_basic_info, :destroy]
  before_action :admin_or_correct_user, only: :show
  before_action :set_one_month, only: :show

  def index
    if params[:user_key]
      @users = User.where('name LIKE ?', "%#{params[:user_key]}%").paginate(page: params[:page])
    else
      @users = User.paginate(page: params[:page])
    end
  end
  
  def show
    @worked_sum = @attendances.where.not(finished_at: nil).count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user
    else
      render :edit_basic_info  
    end
    
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end

    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end
    
    # beforeフィルター
    
    # 管理者権限、または現在ログインしているユーザーを許可します。
    def admin_or_correct_user
#      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  def hour_00(at)
    at.to_s.rjust(2,'0')
  end

  def min_15(at)
    (at.min / 15 * 15).to_s.rjust(2,'0')
  end
  
  def working_times_15(start, finish)
    shour = start.hour
    fhour = finish.hour
    smin_15 = start.min / 15 * 15
    fmin_15 = finish.min / 15 * 15
    
    shour_15 = shour + smin_15 / 60.0
    fhour_15 = fhour + fmin_15 / 60.0

    format("%.2f", fhour_15 - shour_15)
    
  end
    
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages_user', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "Edit-basic-info") %>
<% provide(:class_text, 'basic-info--edit') %>
<% provide(:button_text, '編集') %>
<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user.id), local: true, method: :patch) do |f| %>
      <%= render 'shared/error_messages_user', object: @user %>

      <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, value: "", class: "form-control" %>

      <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_time, value: "", class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% if params[:user_key].nil? || params[:user_key].blank? %>
  <% provide(:title, 'All Users') %>
  <h1>全てのユーザ</h1>
<% else %>
  <% provide(:title, 'Search Results') %>
  <h1>検索結果</h1>
<% end %>
<div id="header">
  <p class="right">ユーザー名検索</p> 
  <div id="nav-search">
    <%= form_with url:users_path, method: :get, local: true do |f| %>
      <div class="input-group">
        <%= text_field_tag :user_key, params[:user_key], placeholder: "キーワードを入力...", class: "form-control" %>
        <span class="input-group-btn">
          <%= button_tag "検索", name: nil, class: "btn btn-primary" %>
        </span>
      </div>
    <% end %>
  </div>
</div>
<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %>　
        |　<%= link_to "基本情報編集", edit_basic_info_user_path(user) %>　
        <% if current_user.admin? && !current_user?(user) %>
        |　<%= link_to "削除", user, method: :delete,
                  data: { confirm: "「#{user.name}」を削除してよろしいですか？" } %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>  
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <% if @month == true %>
          <%= link_to "←", user_path(@user, date: @first_day.prev_month.beginning_of_month, month: true), class: "btn btn-default" %>
        <% elsif @month == false %>
          <%= link_to "←", user_path(@user, date: @first_day.prev_week.beginning_of_week, month: false), class: "btn btn-default" %>
        <% end %>
      　<%= l(@first_day, format: :middle) %>時間管理表
      　<% if @month == true %>
      　   <%= link_to "→", user_path(@user, date: @first_day.next_month.beginning_of_month, month: true), class: "btn btn-default" %>
        <% elsif @month == false %>
          <%= link_to "→", user_path(@user, date: @first_day.next_week.beginning_of_week, month: false), class: "btn btn-default" %>
        <% end %>
      </td>
      <td class="work-time">指定勤務時間　<%= format_basic_info(@user.work_time) %></td>
      <td class="basic-time" colspan="3">基本時間　<%= format_basic_info(@user.basic_time) %></td>
      <td class="first-day">初日　<%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属　<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名　<%= @user.name %></td>
      <td>コード</td>
      <td> </td>
      <td>出勤日数　<%= @worked_sum %>日</td>
      <td>締め　<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class="btn-users-show">
  <% if @month == true %>
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day, month: true), class: "btn btn-primary edit-button" %>
  <% elsif @month == false %>
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day, month: false), class: "btn btn-primary edit-button" %>
  <% end %>
  <% if @month == true %>
    <%= link_to "週表示にする", user_path(@user, date: @first_day.beginning_of_week(:monday), month: false), class: "btn btn-success" %>
  <% elsif @month == false %>
    <%= link_to "月表示にする", user_path(@user, date: @first_day.beginning_of_month, month: true), class: "btn btn-success" %>
  <% end %>
</div>

<div>
  <table class="table table-bordered table-striped table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2" class="date">日付</th>
        <th rowspan="2" class="week">曜日</th>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2" class="col-md-2 working-times">在社時間</th>
        <th rowspan="2" class="col-md-2 note">備考</th>
      </tr>
      <tr>
        <td colspan="1" class="col-md-1">時</td>
        <td colspan="1" class="col-md-1">分</td>
        <td colspan="1" class="col-md-2"></td>
        <td colspan="1" class="col-md-1">時</td>
        <td colspan="1" class="col-md-1">分</td>
        <td colspan="1"></td>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <% if day.worked_on.wday == 0 %>
            <td class="sun"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <% elsif day.worked_on.wday == 6 %>
            <td class="sat"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <% else %>
            <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <% end %>
          <td><%= hour_00(day.started_at.hour) if day.started_at.present? %></td>
          <td><%= min_15(day.started_at) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <% if @month == true %>
                <%= link_to "#{btn_text}", user_attendance_path(@user, day, month: true), method: :patch, class: "btn btn-default btn-attendance" %>
              <% elsif @month == false %>
                <%= link_to "#{btn_text}", user_attendance_path(@user, day, month: false), method: :patch, class: "btn btn-default btn-attendance" %>
              <% end %>
            <% end %>
          </td>
          <td><%= hour_00(day.finished_at.hour) if day.finished_at.present? %></td>
          <td><%= min_15(day.finished_at) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times_15(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan:横結合-->
      <tr>
        <td colspan="2"><%= format_basic_info(@user.basic_time).to_f * @worked_sum %></td>
        <td colspan="6"></td>
        <td colspan="1"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td>所属長承認</td>
      </tr>
    </tfoot>
  </table>
</div>